### ISSUE TITLE
Test on emoji lib data.

### ISSUE THREAD

**Issue by shreyanshu28** [shreyanshu28/slang-translator#8]
See how elasticsearch processes emojis, and in the overall development process of the project.

**Comment by AnuR1234** [comment]
The emojis database has been loaded into ES and was able to test the retrieval of the emoji when its corresponding word is given and vice-versa via Kibana.
For example:
when a word(content) "roar" is given, its corresponding emojis (🐅,🐆) are shown and vice-versa.
